FROM lukechilds/dockerpi

#COPY entr

#WORKDIR /root/

#RUN mkdir -p /usr/aarch64-linux-gnu/lib && ln -s /usr/aarch64-linux-gnu/lib /usr/lib/aarch64-linux-gnu
#RUN dpkg --add-architecture arm64 && apt update && apt upgrade -y && apt update && apt install -y build-essential binutils-multiarch crossbuild-essential-amd64 nano g++-10-aarch64-linux-gnu gcc-10-aarch64-linux-gnu-base cmake vim mc && apt clean
#RUN ln -s /usr/bin/aarch64-linux-gnu-g++-10 /usr/bin/aarch64-linux-gnu-g++ && ln -s /usr/bin/aarch64-linux-gnu-gcc-10 /usr/bin/aarch64-linux-gnu-gcc

#COPY aarch64-linux-gnu-ldd /usr/bin

#RUN apt install g++ gcc valgrind cmake
#RUN apt install -y libwiringpi-dev:arm64